"""
TrendPulse - Task 4: Visualization

Creates a visual dashboard from data/processed_trending_data.csv and saves it as:
reports/trendpulse_dashboard.png
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
DATA_FILE = BASE_DIR / "data" / "processed_trending_data.csv"
REPORTS_DIR = BASE_DIR / "reports"
OUTPUT_FILE = REPORTS_DIR / "trendpulse_dashboard.png"


def shorten(text: str, limit: int = 48) -> str:
    """Shorten long chart labels while preserving readability."""
    text = str(text)
    return text if len(text) <= limit else text[: limit - 1] + "…"


def create_dashboard(df: pd.DataFrame) -> None:
    """Create a four-chart dashboard summarising current trends."""
    if df.empty:
        raise ValueError("Processed dataset is empty.")

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    fig, axes = plt.subplots(2, 2, figsize=(16, 11))
    fig.suptitle(
        "TrendPulse — Live Hacker News Trend Dashboard",
        fontsize=20,
        fontweight="bold",
    )

    # 1. Top 10 stories by trend score.
    top = df.nlargest(10, "trend_score").sort_values("trend_score")
    axes[0, 0].barh(
        [shorten(title) for title in top["title"]],
        top["trend_score"],
    )
    axes[0, 0].set_title("Top 10 Stories by Trend Score")
    axes[0, 0].set_xlabel("Trend score")
    axes[0, 0].grid(axis="x", alpha=0.25)

    # 2. Most frequent domains.
    domains = df["domain"].value_counts().head(10).sort_values()
    axes[0, 1].barh(domains.index, domains.values)
    axes[0, 1].set_title("Top Source Domains")
    axes[0, 1].set_xlabel("Number of stories")
    axes[0, 1].grid(axis="x", alpha=0.25)

    # 3. Score vs comments.
    axes[1, 0].scatter(
        df["score"],
        df["comments"],
        s=(df["trend_score"].clip(lower=1) ** 0.5) * 10,
        alpha=0.65,
    )
    axes[1, 0].set_title("Story Score vs Discussion")
    axes[1, 0].set_xlabel("Score")
    axes[1, 0].set_ylabel("Comments")
    axes[1, 0].grid(alpha=0.25)

    # 4. Story age distribution.
    axes[1, 1].hist(df["age_hours"], bins=12, edgecolor="white")
    axes[1, 1].set_title("Age of Trending Stories")
    axes[1, 1].set_xlabel("Age (hours)")
    axes[1, 1].set_ylabel("Number of stories")
    axes[1, 1].grid(axis="y", alpha=0.25)

    fig.text(
        0.5,
        0.01,
        "Source: Hacker News public API • Generated by TrendPulse",
        ha="center",
        fontsize=10,
    )

    plt.tight_layout(rect=(0, 0.03, 1, 0.95))
    fig.savefig(OUTPUT_FILE, dpi=180, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    if not DATA_FILE.exists():
        raise FileNotFoundError(
            f"{DATA_FILE} does not exist. Run task2_data_processing.py first."
        )

    df = pd.read_csv(DATA_FILE)
    create_dashboard(df)

    print(f"Dashboard saved to: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
